CREATE PROCEDURE USP_GET_ROWS_COUNT @table_name varchar(50) AS
BEGIN

DECLARE @row_count INT;

IF (@table_name = 'JOB_HISTORY')
BEGIN
	SELECT @row_count = CONTEO FROM OPENQUERY(ORACLE_LINK, 'SELECT COUNT(employee_id) AS CONTEO FROM JOB_HISTORY');
END
ELSE IF (@table_name = 'JOBS')
BEGIN
	SELECT @row_count = CONTEO FROM OPENQUERY(ORACLE_LINK, 'SELECT COUNT(job_id) AS CONTEO FROM JOBS');
END
ELSE IF (@table_name = 'DEPARTMENTS')
BEGIN
	SELECT @row_count = CONTEO FROM OPENQUERY(ORACLE_LINK, 'SELECT COUNT(department_id) AS CONTEO FROM DEPARTMENTS');
END
ELSE IF (@table_name = 'LOCATIONS')
BEGIN
	SELECT @row_count = CONTEO FROM OPENQUERY(ORACLE_LINK, 'SELECT COUNT(location_id) AS CONTEO FROM LOCATIONS');
END
ELSE IF (@table_name = 'COUNTRIES')
BEGIN
	SELECT @row_count = CONTEO FROM OPENQUERY(ORACLE_LINK, 'SELECT COUNT(country_id) AS CONTEO FROM COUNTRIES');
END
ELSE IF (@table_name = 'REGIONS')
BEGIN
	SELECT @row_count = CONTEO FROM OPENQUERY(ORACLE_LINK, 'SELECT COUNT(region_id) AS CONTEO FROM REGIONS');
END
ELSE IF (@table_name = 'EMPLOYEES')
BEGIN
	SELECT @row_count = CONTEO FROM OPENQUERY(ORACLE_LINK, 'SELECT COUNT(employee_id) AS CONTEO FROM EMPLOYEES');
END
PRINT (@row_count)
END;